export const LANG = {
  es: {
    // Lobby
    waitingRoom: 'Sala de espera',
    teamsSection: 'Parejas',
    you: 'vos',
    host: 'host',
    spectator: '👁 espectador',
    waitingPartner: 'esperando pareja...',
    joinTeam: 'Unirme',
    leaveTeam: 'Salir',
    newTeam: '+ Nueva pareja',
    noTeam: 'Sin pareja',
    spectatingList: '👁 Especteando',
    players: (n) => `Jugadores (${n})`,
    playBtn: 'Jugar',
    spectateBtn: '👁 Spectate',
    secretCategories: 'Categorias secretas',
    categoriesHint: 'Se revelan cuando empieza la partida.',
    categoryPlaceholder: 'Categoria (ej: Aves)',
    leftExtreme: 'Extremo izq.',
    rightExtreme: 'Extremo der.',
    addCategory: '+ Agregar',
    imported: (ok, skip) => `${ok} categorías importadas${skip ? `, ${skip} filas inválidas` : ''}`,
    addedCategories: (name, n) => `${name} agregó ${n} ${n === 1 ? 'categoria' : 'categorias'}`,
    noCategories: 'Sin categorias aun.',
    config: 'Config',
    configClose: 'cerrar',
    configEdit: 'editar',
    modeLabel: 'Modo',
    spectrumRange: 'Rango del espectro',
    winCondition: 'Victoria',
    points: 'Puntos',
    rounds: 'Rondas',
    pointsPerZone: 'Puntos por zona 🎯',
    zoneBullseye: 'Bullseye',
    zoneClose: 'Cerca',
    zoneNear: 'Casi',
    guessTime: 'Tiempo de adivinación',
    save: 'Guardar',
    startGame: 'Iniciar partida',
    waitingHost: 'Esperando al host...',
    needCategories: 'Agregá al menos una categoría antes de empezar',
    modes: {
      normal: { label: 'Normal',  desc: 'Psychic rotante · poderes activados' },
      teams:  { label: 'Teams',   desc: 'Duos · sin poderes' },
      basta:  { label: 'BASTA',   desc: 'Primero en adivinar lo toma todo' },
    },
    configMode: 'Modo',
    configRange: 'Rango',
    configWin: 'Victoria',
    configTime: 'Tiempo',
    winPoints: (n) => `${n} pts`,
    winRounds: (n) => `${n} rondas`,

    // Game — OtherTeamsStatus
    otherTeams: 'Otros equipos',
    team: (n) => `Equipo ${n}`,
    phaseClue: '🧠 Dando pista…',
    phaseGuessing: '🎯 Adivinando…',
    phaseDone: '✅ Listo',
    guessedCount: (n, t) => `${n}/${t} adivinaron`,
    allTeamsDone: '✅ Todos los equipos terminaron',

    // Game — GameOver
    winnerTeamLabel: 'Equipo ganador',
    teamName: (n) => `Equipo ${n}`,
    totalPts: (n) => `${n} pts en total`,
    returnLobby: 'Volver al lobby',
    winnerLabel: 'Ganador',

    // Game — misc
    noMoreCategories: 'Sin más categorías',
    noMoreCategoriesDesc: 'Se acabaron las cartas del mazo',
    watchingGame: 'Mirando la partida… 👁',
    preparingRound: 'Preparando ronda...',
    roundLabel: (n) => `Ronda ${n}`,
    goalPts: (n) => `Meta: ${n} pts`,
    roundsGoal: (cur, total) => `${cur} / ${total} rondas`,
    nextRound: 'Siguiente ronda',
    waitingOtherTeam: 'Esperando que el otro equipo termine…',
    revealNow: 'Revelar ahora',

    // ClueGiving
    youArePsychic: '¡Sos el Psychic!',
    psychicThinking: (name) => `${name} está pensando...`,
    clueHint: (cat) => `Dá una pista que ubique el espectro en ${cat}`,
    cluePlaceholder: 'Tu pista...',
    send: 'Enviar',
    waitingClue: 'Esperando la pista del Psychic...',
    roundLabel2: (n) => `RONDA ${n}`,

    // Guessing
    roundGuess: (n) => `RONDA ${n} · ADIVINANZA`,
    saidClue: (name) => `dijo ${name}`,
    psychicCantGuess: 'Sos el Psychic — no podés adivinar',
    spectatorRound: '👁 Estás especteando esta ronda',
    blocked: '🚫 Estás bloqueado esta ronda',
    bastaInfo: '⚡ El primero en adivinar es el único que puede ganar puntos',
    bastaConfirm: '⚡ ¡BASTA! Confirmar',
    confirmGuess: 'Confirmar adivinanza',
    bastaHint: 'Click o Espacio para cantar BASTA',
    guessHint: 'Arrastrá la aguja y confirmá tu posición',
    guessSent: '✓ Adivinanza enviada',

    // Revealing
    revealTitle: '¡Reveal!',
    categoryOf: (name) => `Categoría de: ${name}`,
    bullseyeFreePower: '¡Bullseye! Poder gratis',
    bullseyeFreePowerDesc: 'Vas a recibir un poder gratis al inicio de la próxima ronda',
    arrivalOrder: '⚡ Orden de llegada',
    powersUsed: '⚡ Poderes usados esta ronda',
    reasonLabels: {
      psychic_good_clue: { label: '🧠 Buena pista',   color: '#10b981' },
      psychic_no_hits:   { label: '💀 Nadie adivinó', color: '#ef4444' },
      bullseye:          { label: '🎯 Bullseye!',      color: '#ef4444' },
      close:             { label: '🔥 Cerca',          color: '#f97316' },
      near:              { label: '✓ Cerca',           color: '#fbbf24' },
      miss:              { label: '✗ Errado',          color: '#6b7280' },
      miss_escudo:       { label: '🛡️ Escudo',        color: '#3b82f6' },
      miss_penalty:      { label: '⚠️ Penalidad',     color: '#ef4444' },
      basta_not_first:   { label: '—',                color: '#6b7280' },
      basta_others_win:  { label: '+1 🎉',            color: '#10b981' },
      cuartiles_bullseye:{ label: '🎯 Cuartil!',      color: '#ef4444' },
      cuartiles_close:   { label: '🔥 Cuartil',       color: '#f97316' },
      cuartiles_hit:     { label: '✓ Cuartil',        color: '#fbbf24' },
      cuartiles_miss:    { label: '✗ Cuartil',        color: '#6b7280' },
      bloqueo_blocked:   { label: '🚫 Bloqueado',     color: '#ef4444' },
      veneno_taken:      { label: '☠️ Veneno',        color: '#8b5cf6' },
    },
    powerUseLabels: {
      cuartiles: 'usó Cuartiles', veneno: 'tiró Veneno a',
      escudo: 'usó Escudo', bloqueo: 'bloqueó a', switch: 'hizo Switch con',
    },

    // PowerCard
    redeemFree: 'Canjear gratis',
    buy: 'Comprar',
    reserved: '⏳ Reservado',
    reserve: 'Reservar',
    use: 'Usar',
    powersTitle: 'Poderes',
    activatesOnGuess: '⏳ se activa al adivinar',
    freePowerBullseye: '¡Poder gratis por bullseye!',
    costLabel: 'Costo',
    savedInventory: '— se guardan en tu inventario',
    autoActivate: 'El efecto se activará automáticamente cuando empiece la adivinación',
    choosePlayer: 'Elegí un jugador:',
    cancel: 'Cancelar',
  },

  en: {
    // Lobby
    waitingRoom: 'Waiting room',
    teamsSection: 'Teams',
    you: 'you',
    host: 'host',
    spectator: '👁 spectator',
    waitingPartner: 'waiting for partner...',
    joinTeam: 'Join',
    leaveTeam: 'Leave',
    newTeam: '+ New team',
    noTeam: 'No team',
    spectatingList: '👁 Spectating',
    players: (n) => `Players (${n})`,
    playBtn: 'Play',
    spectateBtn: '👁 Spectate',
    secretCategories: 'Secret categories',
    categoriesHint: 'Revealed when the game starts.',
    categoryPlaceholder: 'Category (e.g. Birds)',
    leftExtreme: 'Left extreme',
    rightExtreme: 'Right extreme',
    addCategory: '+ Add',
    imported: (ok, skip) => `${ok} categories imported${skip ? `, ${skip} invalid rows` : ''}`,
    addedCategories: (name, n) => `${name} added ${n} ${n === 1 ? 'category' : 'categories'}`,
    noCategories: 'No categories yet.',
    config: 'Config',
    configClose: 'close',
    configEdit: 'edit',
    modeLabel: 'Mode',
    spectrumRange: 'Spectrum range',
    winCondition: 'Win condition',
    points: 'Points',
    rounds: 'Rounds',
    pointsPerZone: 'Points per zone 🎯',
    zoneBullseye: 'Bullseye',
    zoneClose: 'Close',
    zoneNear: 'Near',
    guessTime: 'Guess time',
    save: 'Save',
    startGame: 'Start game',
    waitingHost: 'Waiting for host...',
    needCategories: 'Add at least one category before starting',
    modes: {
      normal: { label: 'Normal', desc: 'Rotating psychic · powers enabled' },
      teams:  { label: 'Teams',  desc: 'Duos · no powers' },
      basta:  { label: 'BASTA',  desc: 'First to guess takes all' },
    },
    configMode: 'Mode',
    configRange: 'Range',
    configWin: 'Win',
    configTime: 'Time',
    winPoints: (n) => `${n} pts`,
    winRounds: (n) => `${n} rounds`,

    // Game — OtherTeamsStatus
    otherTeams: 'Other teams',
    team: (n) => `Team ${n}`,
    phaseClue: '🧠 Giving clue…',
    phaseGuessing: '🎯 Guessing…',
    phaseDone: '✅ Done',
    guessedCount: (n, t) => `${n}/${t} guessed`,
    allTeamsDone: '✅ All teams finished',

    // Game — GameOver
    winnerTeamLabel: 'Winning team',
    teamName: (n) => `Team ${n}`,
    totalPts: (n) => `${n} pts total`,
    returnLobby: 'Back to lobby',
    winnerLabel: 'Winner',

    // Game — misc
    noMoreCategories: 'No more categories',
    noMoreCategoriesDesc: 'The deck ran out',
    watchingGame: 'Watching the game… 👁',
    preparingRound: 'Preparing round...',
    roundLabel: (n) => `Round ${n}`,
    goalPts: (n) => `Goal: ${n} pts`,
    roundsGoal: (cur, total) => `${cur} / ${total} rounds`,
    nextRound: 'Next round',
    waitingOtherTeam: 'Waiting for the other team to finish…',
    revealNow: 'Reveal now',

    // ClueGiving
    youArePsychic: "You're the Psychic!",
    psychicThinking: (name) => `${name} is thinking...`,
    clueHint: (cat) => `Give a clue to place the spectrum on ${cat}`,
    cluePlaceholder: 'Your clue...',
    send: 'Send',
    waitingClue: "Waiting for the Psychic's clue...",
    roundLabel2: (n) => `ROUND ${n}`,

    // Guessing
    roundGuess: (n) => `ROUND ${n} · GUESS`,
    saidClue: (name) => `said by ${name}`,
    psychicCantGuess: "You're the Psychic — you can't guess",
    spectatorRound: '👁 You are spectating this round',
    blocked: '🚫 You are blocked this round',
    bastaInfo: '⚡ The first to guess is the only one who can score',
    bastaConfirm: '⚡ BASTA! Confirm',
    confirmGuess: 'Confirm guess',
    bastaHint: 'Click or Space to call BASTA',
    guessHint: 'Drag the needle and confirm your position',
    guessSent: '✓ Guess submitted',

    // Revealing
    revealTitle: 'Reveal!',
    categoryOf: (name) => `Category by: ${name}`,
    bullseyeFreePower: 'Bullseye! Free power',
    bullseyeFreePowerDesc: 'You will receive a free power at the start of the next round',
    arrivalOrder: '⚡ Arrival order',
    powersUsed: '⚡ Powers used this round',
    reasonLabels: {
      psychic_good_clue: { label: '🧠 Good clue',      color: '#10b981' },
      psychic_no_hits:   { label: '💀 Nobody guessed',  color: '#ef4444' },
      bullseye:          { label: '🎯 Bullseye!',        color: '#ef4444' },
      close:             { label: '🔥 Close',            color: '#f97316' },
      near:              { label: '✓ Near',              color: '#fbbf24' },
      miss:              { label: '✗ Miss',              color: '#6b7280' },
      miss_escudo:       { label: '🛡️ Shield',          color: '#3b82f6' },
      miss_penalty:      { label: '⚠️ Penalty',         color: '#ef4444' },
      basta_not_first:   { label: '—',                  color: '#6b7280' },
      basta_others_win:  { label: '+1 🎉',              color: '#10b981' },
      cuartiles_bullseye:{ label: '🎯 Quartile!',       color: '#ef4444' },
      cuartiles_close:   { label: '🔥 Quartile',        color: '#f97316' },
      cuartiles_hit:     { label: '✓ Quartile',         color: '#fbbf24' },
      cuartiles_miss:    { label: '✗ Quartile',         color: '#6b7280' },
      bloqueo_blocked:   { label: '🚫 Blocked',         color: '#ef4444' },
      veneno_taken:      { label: '☠️ Poisoned',        color: '#8b5cf6' },
    },
    powerUseLabels: {
      cuartiles: 'used Quartiles', veneno: 'poisoned',
      escudo: 'used Shield', bloqueo: 'blocked', switch: 'switched with',
    },

    // PowerCard
    redeemFree: 'Redeem free',
    buy: 'Buy',
    reserved: '⏳ Reserved',
    reserve: 'Reserve',
    use: 'Use',
    powersTitle: 'Powers',
    activatesOnGuess: '⏳ activates on guess',
    freePowerBullseye: 'Free power from bullseye!',
    costLabel: 'Cost',
    savedInventory: '— saved in your inventory',
    autoActivate: 'The effect will activate automatically when guessing begins',
    choosePlayer: 'Choose a player:',
    cancel: 'Cancel',
  },
};
